### PR TITLE
Fix loc_trajectory and per_loc function 

### LINKED ISSUE #427: Error: `loc_trajectory` and `per_loc` not qualifying `dim`
When running 

```julia
tac = ADRIA.metrics.total_absolute_cover(rs)
m_tac = ADRIA.metrics.loc_trajectory(median, tac)
```

and, inside `viz/clustering.jl` `map!` function

```julia
opts[:summary] = get(opts, :summary, mean)
data_stats = collect(ADRIA.metrics.per_loc(opts[:summary], data))
```

I got the same error:

```
WARNING: both NamedDims and Distributions export "dim"; uses of it in module metrics must be qualified
ERROR: UndefVarError: `dim` not defined
Stacktrace:
 [1] loc_trajectory(metric::Function, data::NamedDims.NamedDimsArray{(:timesteps, :sites, :scenarios), Float32, 3, AxisKeys.KeyedArray{Float32, 3, Zarr.ZArray{Float32, 3, Zarr.BloscCompressor, Zarr.DirectoryStore}, Tuple{Vector{Any}, Vector{Any}, UnitRange{Int64}}}})
   @ ADRIA.metrics C:\Users\pribeiro\AIMS\Code\ADRIA.jl\src\metrics\site_level.jl:72
 [2] top-level scope
   @ c:\Users\pribeiro\AIMS\Code\ADRIA.jl\sandbox\time_series_clusters\tsc_map.jl:23
```

### PR DESCRIPTION
**Pull request by Zapiano**
`loc_trajectory` and `per_loc` calls to `dim` are raising a `not defined` error. The fix for this is to qualify these calls with `NamedDims.dim` 

Closes #427

### CODE REVIEW

File: src/metrics/site_level.jl [hunk 1]
```diff
@@ -23,7 +23,11 @@ function per_loc(metric, data::NamedDimsArray{D,T,N,A})::NamedDimsArray where {D
     #   see: https://stackoverflow.com/a/62040897
     tf = axes(data, :timesteps)
     s::Vector{eltype(data)} = map(metric,
-        JuliennedArrays.Slices(data[timesteps=tf], dim(data, :timesteps), dim(data, :scenarios))
+        JuliennedArrays.Slices(
+            data[timesteps=tf],
+            NamedDims.dim(data, :timesteps),
+            NamedDims.dim(data, :scenarios)
```
Comment (ConnectedSystems) [inline src/metrics/site_level.jl:29]: How about we standardize to `axiskeys()`

```suggestion
            axiskeys(data, :timesteps),
            axiskeys(data, :scenarios)
```

**Review by ConnectedSystems — APPROVED** [review]
Thanks
