### PR TITLE
Fix rule extraction to handle constant factors

### LINKED ISSUE #672: Ignore constant factors when applying SIRUS
Leads to an error about `_rules!()` keyword parameter not being defined in cases where non-constant factors are provided to SIRUS.

Ignoring constant factors resolves the issue, and probably should be done as part of `cluster_rules()`

```julia
fields_iv = ADRIA.component_params(rs_all, [Intervention, CriteriaWeights]).fieldname
varying_factor_idx = .!rs_all.model_spec.is_constant
varying_factor_names = rs_all.model_spec.fieldname[varying_factor_idx]
 
foi_idx = map(x -> x ∈ varying_factor_names, fields_iv)
fields_iv = fields_iv[foi_idx]
 
scenarios_iv = all_scens[:, fields_iv]
 
n_clusters = 4
clusters = ADRIA.analysis.cluster_scenarios(stac, n_clusters)
target_clusters = ADRIA.analysis.target_clusters(clusters, stac)
 
max_rules = 4
rules_iv = ADRIA.analysis.cluster_rules(target_clusters, scenarios_iv, max_rules)
 
rules_scatter_fig = ADRIA.viz.rules_scatter(
    rs_all,
    scenarios_iv,
    target_clusters,
    rules_iv;
    fig_opts=Dict(:size=>(1000, 800))
    # opts=opts
)
```

### PR DESCRIPTION
**Pull request by Zapiano**
Note: This branch is based on #863 's branch. Closes #672 .

---

Updates `ADRIA.analysis.cluster_rules` so we can check for constant factors (and ignore them) before trying to extract rules. The parameters you need to pass to `cluster_rules` have changed - with that is one line less of code now.

The documentation still needs to be updated - once this is done, I'll mark this as ready to review.

## Example
As an example, let's fix all `SeedCriteriaWeights` and only a few of the `FogCriteriaWeights` factors, run the model, cluster and target some cluster:

```
dom = ADRIA.load_domain("...")

ADRIA.fix_factor!(
    dom;
    # Seed criteria
    seed_out_connectivity=0.9,
    seed_heat_stress=0.8,
    seed_depth=0.7,
    seed_coral_cover=0.5,
    seed_in_connectivity=0.4,
    seed_wave_stress=0.0,
    # Fog criteria
    fog_coral_cover=0.5,
    fog_depth=0.7
)

# Create scenarios
num_scens = 2^8
scens = ADRIA.sample(dom, num_scens)

# Run model / Load ResultSet
rs = ADRIA.run_scenarios(dom, scens, "45")

# Find Time Series Clusters
s_tac = ADRIA.metrics.scenario_total_cover(rs)
num_clusters = 6
clusters = ADRIA.analysis.cluster_scenarios(s_tac, num_clusters)

# Target scenarios
target_clusters = ADRIA.analysis.target_clusters(clusters, s_tac)
```

Now if we select `Intervention` factors, everything works (as it would previously, nothing's c hanged here):

```
max_rules = 10
fields_iv = ADRIA.component_params(rs, [Intervention]).fieldname
rules_iv = ADRIA.analysis.cluster_rules(dom, target_clusters, scens, fields_iv, max_rules)
```

If we select `FogCriteriaWeights`, some are constant and some are not. Previously this would lead to an error but now it just filters off all constant factors and everything works fine:

```
max_rules = 10
fields_fog = ADRIA.component_params(rs, [FogCriteriaWeights]).fieldname
rules_fog = ADRIA.analysis.cluster_rules(
    dom, target_clusters, scens, fields_seeds, max_rules
)
```

And, finally, if we select `SeedCriteriaWeights`, because all of them are constant, this will raise an error:

```
max_rules = 10
fields_seeds = ADRIA.component_params(rs, [SeedCriteriaWeights]).fieldname
rules_seeds = ADRIA.analysis.cluster_rules(
    dom, target_clusters, scens, fields_seeds, max_rules
)
```

The error:

```
ERROR: ArgumentError: Factors of interest have to be non constant.
Stacktrace:
 [1] cluster_rules(domain::ADRIADomain, clusters::Vector{…}, scenarios::DataFrames.DataFrame, factors::Vector{…}, max_rules::Int64; seed::Int64, kwargs::@Kwargs{})
   @ ADRIA.analysis c:\Users\pribeiro\AIMS\Code\ADRIA.jl\src\analysis\rule_extraction.jl:148
 [2] cluster_rules(domain::ADRIADomain, clusters::Vector{…}, scenarios::DataFrames.DataFrame, factors::Vector{…}, max_rules::Int64)
   @ ADRIA.analysis c:\Users\pribeiro\AIMS\Code\ADRIA.jl\src\analysis\rule_extraction.jl:134
 [3] top-level scope
   @ c:\Users\pribeiro\AIMS\Code\ADRIA.jl\sandbox\rule_extraction\fixed_factors.jl:77
Some type information was truncated. Use `show(err)` to see complete types.
```

Below are the scatter plots for `Interventions` and `FogCriteriaWeights` rules (the plot functions haven't changed):

| `Intervention` | `FogCriteriaWeights` |
| -- | -- |
| rules_iv_scatter | rules_fog_scatter |

### CODE REVIEW

**Comment by ConnectedSystems** [comment]
Haven't looked through the changes yet (will wait for the dependent PR to be merged first), but one minor request:

Change the message to "Factors of interest cannot be constant".

**Comment by Zapiano** [comment]
@ConnectedSystems  this one is ready for review.

**Comment by Zapiano** [comment]
@ConnectedSystems friendly reminder that this is ready for review

File: src/analysis/rule_extraction.jl [hunk 1]
```diff
@@ -129,8 +132,24 @@ A StableRules object (implemented by SIRUS).
    Electron. J. Statist. 15 (1) 427 - 505.
    https://doi.org//10.1214/20-EJS1792
 """
-function cluster_rules(clusters::Vector{T}, X::DataFrame, max_rules::T;
-    seed::Int64=123, kwargs...) where {T<:Int64}
+function cluster_rules(
+    result_set::ADRIA.ResultSet,
```
Comment (ConnectedSystems) [inline src/analysis/rule_extraction.jl:136]: Minor comment - could this be simplified to `ResultSet`? If not, maybe we should consider exporting the `ResultSet` type...

**Review by ConnectedSystems — APPROVED** [review]
Just one minor question.

Otherwise this is ready to be merged.

File: src/analysis/rule_extraction.jl (hunk 1 above)
Comment (Zapiano) [reply src/analysis/rule_extraction.jl]: Yep, that works.

**Comment by Zapiano** [comment]
I still need to rebase this.

**Comment by Zapiano** [comment]
@ConnectedSystems this one is rebased and ready for review.
